"""
1e-12 fidelity replay test.

Verifies that loading model_pipeline.pkl and running it on a fixed 100-row sample
produces bit-for-bit identical probabilities to the saved reference (fidelity_proba_ref.npy).

Both artifacts are generated by train.py and committed to the repo.
Skips gracefully if either file is missing (i.e., model not yet trained in CI).
"""

from pathlib import Path

import numpy as np
import pytest

TRAINING_DIR = Path(__file__).parent.parent.parent / "training"
PKL_PATH = TRAINING_DIR / "model_pipeline.pkl"
SAMPLE_PATH = TRAINING_DIR / "fidelity_sample.json"
REF_PATH = TRAINING_DIR / "fidelity_proba_ref.npy"


@pytest.fixture(scope="module")
def fidelity_artifacts():
    if not PKL_PATH.exists():
        pytest.skip("model_pipeline.pkl not found — run training/train.py first")
    if not SAMPLE_PATH.exists() or not REF_PATH.exists():
        pytest.skip("fidelity_sample.json or fidelity_proba_ref.npy not found — run training/train.py first")

    import joblib
    import json
    import pandas as pd

    model = joblib.load(PKL_PATH)
    rows = json.loads(SAMPLE_PATH.read_text())
    X = pd.DataFrame(rows)
    ref_proba = np.load(str(REF_PATH))
    return model, X, ref_proba


def test_fidelity_replay_atol_1e12(fidelity_artifacts):
    """Loaded model must reproduce saved probabilities to within 1e-12."""
    model, X, ref_proba = fidelity_artifacts
    current_proba = model.predict_proba(X)[:, 1]
    assert np.allclose(current_proba, ref_proba, atol=1e-12), (
        f"Fidelity check failed — max diff: {np.abs(current_proba - ref_proba).max():.2e}"
    )


def test_fidelity_sample_row_count(fidelity_artifacts):
    """Sanity: sample must have exactly 100 rows."""
    _, X, ref_proba = fidelity_artifacts
    assert len(X) == 100
    assert len(ref_proba) == 100
